---
language: ruby
services:
    - docker
branches:
    only:
        - master
env:
   global:
    - DEST_ID=core
    - NSVER=7
    - DOCKER_IMAGE=nethserver/makerpms:${NSVER}
    - >
        EVARS="
        -e DEST_ID
        -e TRAVIS_BRANCH
        -e TRAVIS_BUILD_ID
        -e TRAVIS_PULL_REQUEST_BRANCH
        -e TRAVIS_PULL_REQUEST
        -e TRAVIS_REPO_SLUG
        -e TRAVIS_TAG
        -e NSVER
        -e ENDPOINTS_PACK
        "

script: >
    version=$(sed -n -r '/^Version:/ { s/Version: +// ; p }' nethserver-subscription.spec) ;
    sed -r -i "/^Version:/ s/Version:.*/Version: ${version}/" nethserver-subscription-inventory.spec ;
    sed -r -n '/^%changelog/,$ p' nethserver-subscription.spec >> nethserver-subscription-inventory.spec ;
    for spec in nethserver-subscription-inventory.spec nethserver-subscription.spec; do
    docker run -ti --name makerpms-${spec} ${EVARS}
    --hostname b${TRAVIS_BUILD_NUMBER}.nethserver.org
    --volume $PWD:/srv/makerpms/src:ro ${DOCKER_IMAGE} makerpms-travis -s ${spec}
    && docker commit makerpms-${spec} nethserver/build-${spec}
    && docker run -ti ${EVARS}
    -e SECRET
    -e SECRET_URL
    -e AUTOBUILD_SECRET
    -e AUTOBUILD_SECRET_URL
    nethserver/build-${spec} uploadrpms-travis ;
    done
